require:
  - rubocop-rake
  - rubocop-rspec


AllCops:
  TargetRubyVersion: 3.2.8

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
